rubric:
  possibleScore:
  - requirement: repo contains starter/hello.c that prints "hello, world"
    points: 10
  - requirement: quality of question answers in the questions.md file
    points: 10
  possibleExtraCreditScore: []
  requirements:
  - description: submit a working hello world program
    criteria:
    - must compile and run without errors
    - must print "hello, world" to stdout
    - must pass make test
  - description: answer the questions in questions.md
    criteria:
    - must place each quesiton answer after the question in questions.md
    - must provide a complete, correct, and thorough answer



